CREATE TABLE [dbo].[Arquivo]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[Nome] VARCHAR(255) NOT NULL,
	[Endereco] VARCHAR(500) NOT NULL,
	[Tipo] VARCHAR(100) NOT NULL,
	[Tamanho] INT NOT NULL DEFAULT 0,
	[DataCriacao] DATETIME NOT NULL
)
